---

#
# node.js hosts! check the readme on how to add more
# (if its not obvious enough).
#

hosts:

  - infra:

    - digitalocean:
        ubuntu1404-x64-1: {ip: 107.170.240.62, alias: ci}
        ubuntu1604-x64-1: {ip: 138.197.224.240, alias: www}
        ubuntu1804-x64-1: {ip: 178.128.202.158, alias: gzemnid}
        ubuntu1804-x64-2: {ip: 45.55.45.227, alias: unofficial-builds}

    - joyent:
        smartos15-x64-1: {ip: 165.225.151.21, alias: backup}
        ubuntu1604-x64-1: {ip: 165.225.149.55, alias: unencrypted}

    - rackspace:
        debian8-x64-1: {ip: 23.253.100.79, alias: gh-bot}

    - softlayer:
        debian8-x64-1: {ip: 184.172.29.199, alias: registry-mirror}
        ubuntu1404-x64-1: {ip: 169.44.16.104, alias: ci-release}
        ubuntu1404-x64-2: {ip: 50.23.85.254}


  - release:

    - digitalocean:
        centos6-x86-1: {ip: 162.243.248.28}
        centos7-x64-1: {ip: 138.68.12.105}

    - ibm:
        aix71-ppc64_be-1: {ip: 129.33.196.199, user: b9s010a}
        rhel7-s390x-1: {ip: 148.100.86.101, user: linux1}

    - iinthecloud:
        ibmi72-ppc64_be-1: {ip: 65.183.160.62, user: nodejs}

    - joyent:
        smartos15-x64-2: {ip: 165.225.148.139}
        smartos17-x64-2: {ip: 165.225.149.208}
        smartos18-x64-2: {ip: 165.225.148.12}
        ubuntu1804_docker-x64-1: {ip: 165.225.150.76, user: ubuntu}

    - macstadium:
        macos10.11-x64-1: {ip: 207.254.58.162, port: 10013, user: administrator}
        macos10.10-x64-1: {ip: 207.254.58.162, port: 10014, user: administrator}

    - marist:
        zos13-s390x-1: {ip: 148.100.36.135, user: Unix1}

    - nearform:
        macos10.15-x64-1: {ip: 83.147.191.69, user: administrator}

    - osuosl:
        centos7-ppc64_le-1: {ip: 140.211.168.61, user: centos}

    - orka:
        macos10.15-x64-1: {ip: 199.7.167.101, port: 8822, user: administrator}

    - packetnet:
        centos7-arm64-1: {ip: 147.75.104.218}

    - requireio:
        rvagg-debian10-armv6l_pi1p-1: {ip: 192.168.2.40, user: pi, alias: iojs-ns-pi1p-1 }
        andineck-debian10-armv6l_pi1p-1: {ip: 192.168.2.41, user: pi, alias: iojs-ns-pi1p-2 }
        osx1010-x64-1: {ip: 192.168.2.211, user: iojs}

    - scaleway:
        ubuntu1604-armv7l-1: {ip: 212.47.245.242}
        ubuntu1604-armv7l-2: {ip: 212.47.234.107}

    - softlayer:
        centos6-x64-1: {ip: 50.97.245.10}






  - test:

    - azure:
        msft-win10_vcbt2015-x64-1: {ip: nodejs.eastus2.cloudapp.azure.com}
        msft-win10_vcbt2015-x64-2: {ip: nodejs.westus2.cloudapp.azure.com}
        msft-win10_vcbt2015-x64-3: {ip: nodejs.eastus2.cloudapp.azure.com}
        msft-win10_vcbt2015-x64-4: {ip: nodejs.westus2.cloudapp.azure.com}
        msft-win10_vs2019-x64-1: {ip: nodejs.eastus2.cloudapp.azure.com}
        msft-win10_vs2019-x64-2: {ip: nodejs.westus2.cloudapp.azure.com}
        msft-win10_vs2019-x64-3: {ip: nodejs.eastus2.cloudapp.azure.com}
        msft-win10_vs2019-x64-4: {ip: nodejs.westus2.cloudapp.azure.com}
        msft-win2016_vs2017-x64-1: {ip: nodejs.eastus2.cloudapp.azure.com}
        msft-win2016_vs2017-x64-2: {ip: nodejs.westus2.cloudapp.azure.com}
        msft-win2016_vs2017-x64-3: {ip: nodejs.eastus2.cloudapp.azure.com}
        msft-win2016_vs2017-x64-4: {ip: nodejs.westus2.cloudapp.azure.com}
        msft-win2016_vs2017-x64-5: {ip: nodejs.eastus2.cloudapp.azure.com}
        msft-win2016_vs2017-x64-6: {ip: nodejs.westus2.cloudapp.azure.com}

    - digitalocean:
        debian8-x64-1: {ip: 159.203.103.52}
        debian9-x64-1: {ip: 138.197.97.208}
        fedora27-x64-1: {ip: 159.203.117.50}
        fedora30-x64-1: {ip: 178.62.236.249}
        fedora30-x64-2: {ip: 159.203.98.84}
        freebsd11-x64-1: {ip: 45.55.90.237, user: freebsd}
        freebsd11-x64-2: {ip: 107.170.28.213, user: freebsd}
        ubuntu1404-x64-1: {ip: 45.55.252.223}
        ubuntu1404-x86-1: {ip: 159.203.115.220}
        ubuntu1604-x86-1: {ip: 159.203.77.233}
        ubuntu1604-x86-2: {ip: 104.131.191.135}
        ubuntu1804_docker-x64-1: {ip: 134.209.55.216}
        ubuntu1804_docker-x64-2: {ip: 159.89.183.200}
        ubuntu1804-x64-1: {ip: 178.128.181.213}

    - ibm:
        aix71-ppc64_be-1: {ip: 129.33.196.197, user: b9s010a}
        aix71-ppc64_be-2: {ip: 129.33.196.198, user: b9s010a}
        rhel7-s390x-1: {ip: 148.100.86.21, user: linux1}
        rhel7-s390x-2: {ip: 148.100.86.117, user: linux1}
        rhel7-s390x-3: {ip: 148.100.86.28, user: linux1}
        rhel7-s390x-4: {ip: 148.100.86.94, user: linux1}
        ubuntu1804-x64-1: {ip: 52.117.26.14, alias: jenkins-workspace-6}

    - joyent:
        smartos15-x64-3: {ip: 165.225.148.128}
        smartos15-x64-4: {ip: 165.225.149.91}
        smartos16-x64-3: {ip: 165.225.151.106}
        smartos16-x64-4: {ip: 165.225.149.158}
        smartos17-x64-3: {ip: 165.225.148.15}
        smartos17-x64-4: {ip: 165.225.148.16}
        smartos18-x64-3: {ip: 165.225.151.114}
        smartos18-x64-4: {ip: 165.225.149.13}
        ubuntu1804_docker-x64-1: {ip: 165.225.151.201, user: ubuntu}
        ubuntu1804-x64-1: {ip: 165.225.149.88, user: ubuntu}

    - marist:
        zos13-s390x-1:
            ip: 148.100.36.133
            user: Unix1
            remote_env:
                LIBPATH: /lib:/usr/lib:.:/NODEJS2/lib/perl5/5.24.0/os390/CORE.pod:/NODEJS2/python-2017-04-12-py27/python27/lib/
                PATH: /NODEJS2/python-2017-04-12-py27/python27/bin:/bin:/NODEJS2/bin:/NODEJS/bin
            server_jobs: 4
        zos13-s390x-2:
            ip: 148.100.36.134
            user: Unix1
            remote_env:
                LIBPATH: /lib:/usr/lib:.:/NODEJS2/lib/perl5/5.24.0/os390/CORE.pod:/NODEJS2/python-2017-04-12-py27/python27/lib/
                PATH: /NODEJS2/python-2017-04-12-py27/python27/bin:/bin:/NODEJS2/bin:/NODEJS/bin
            server_jobs: 4

    - mininodes:
        ubuntu1604-arm64_odroid_c2-1: {ip: 70.167.220.147}
        ubuntu1604-arm64_odroid_c2-2: {ip: 70.167.220.148}
        ubuntu1604-arm64_odroid_c2-3: {ip: 70.167.220.149, user: odroid}

    - macstadium:
        macos10.10-x64-1: {ip: 207.254.58.162, port: 10005, user: administrator}
        macos10.10-x64-2: {ip: 207.254.58.162, port: 10006, user: administrator}
        macos10.11-x64-1: {ip: 207.254.58.162, port: 10003, user: administrator}
        macos10.11-x64-2: {ip: 207.254.58.162, port: 10004, user: administrator}
        macos10.12-x64-1: {ip: 207.254.58.162, port: 10001, user: administrator}
        macos10.12-x64-2: {ip: 207.254.58.162, port: 10002, user: administrator}

    - msft:
        win10_vs2017-arm64-1: {}
        win10_vs2017-arm64-2: {}

    - nearform:
        macos10.15-x64-1: {ip: 83.147.191.70, user: administrator}
        macos10.15-x64-2: {ip: 83.147.191.71, user: administrator}
        macos10.15-x64-3: {ip: 83.147.191.72, user: administrator}
        intel-ubuntu1604-x64-1: {ip: 92.51.196.114}
        intel-ubuntu1604-x64-2: {ip: 92.51.196.115}


    - osuosl:
# secret for -1 was compromised, do not use -1 name
        aix72-ppc64_be-2: {ip: 140.211.9.30}
        centos7-ppc64_le-1: {ip: 140.211.168.193, user: centos}
        centos7-ppc64_le-2: {ip: 140.211.168.244, user: centos}

    - orka:
        macos10.15-x64-1: {ip: 199.7.167.100, port: 8823, user: administrator}
        macos10.15-x64-2: {ip: 199.7.167.99, port: 8823, user: administrator}
        macos10.14-x64-1: {ip: 199.7.167.99, port: 8822, user: administrator}
        macos10.14-x64-2: {ip: 199.7.167.100, port: 8824, user: administrator}
        macos10.14-x64-3: {ip: 199.7.167.101, port: 8824, user: administrator}

    - iinthecloud:
        ibmi72-ppc64_be-1: {ip: 65.183.160.52, user: nodejs}
        ibmi72-ppc64_be-2: {ip: 65.183.160.59, user: nodejs}

    - rackspace:
        centos7-x64-1: {ip: 119.9.27.82}
        debian8-x64-1: {ip: 23.253.109.216}
        debian8-x64-2: {ip: 104.239.140.184}
        fedora27-x64-1: {ip: 119.9.51.79}
        ubuntu1604-x64-1: {ip: 119.9.51.176}
        ubuntu1604-x64-2: {ip: 104.130.124.194}
        win2012r2_vs2013-x64-1: {ip: 104.239.174.165}
        win2012r2_vs2013-x64-2: {ip: 104.130.132.171}
        win2012r2_vs2015-x64-1: {ip: 104.239.174.8}
        win2012r2_vs2015-x64-2: {ip: 104.130.141.137}
        win2012r2_vs2017-x64-1: {ip: 162.242.237.72}
        win2012r2_vs2017-x64-2: {ip: 104.239.142.99}
        win2012r2_vs2017-x64-3: {ip: 119.9.131.54}
        win2012r2_vs2017-x64-4: {ip: 166.78.99.25}
        win2012r2_vs2019-x64-1: {ip: 162.242.237.124}
        win2012r2_vs2019-x64-2: {ip: 104.130.158.58}
        win2012r2_vs2019-x64-3: {ip: 119.9.131.63}
        win2012r2_vs2019-x64-4: {ip: 104.130.219.103}
        win2012r2_vs2019-x64-5: {ip: 104.130.6.92}
        win2012r2_vs2019-x64-6: {ip: 104.130.141.231}

    - requireio:
        andineck-debian10-armv6l_pi1p-1:         {ip: 192.168.2.42, user: pi, alias: iojs-ns-pi1p-3 }
        bengl-debian10-armv6l_pi1p-1:            {ip: 192.168.2.43, user: pi, alias: iojs-ns-pi1p-4 }
        bengl-debian10-armv6l_pi1p-2:            {ip: 192.168.2.44, user: pi, alias: iojs-ns-pi1p-5}
        continuationlabs-debian10-armv6l_pi1p-1: {ip: 192.168.2.45, user: pi, alias: iojs-ns-pi1p-6 }
        ceejbot-debian10-armv6l_pi1p-1:          {ip: 192.168.2.46, user: pi, alias: iojs-ns-pi1p-7 }
        mininodes-debian10-armv6l_pi1p-1:        {ip: 192.168.2.47, user: pi, alias: iojs-ns-pi1p-8 }
        indieisaconcept-debian10-armv6l_pi1p-1:  {ip: 192.168.2.48, user: pi, alias: iojs-ns-pi1p-9 }
        mhdawson-debian10-armv6l_pi1p-1:         {ip: 192.168.2.49, user: pi, alias: iojs-ns-pi1p-10 }
        securogroup-debian10-armv6l_pi1p-1:      {ip: 192.168.2.50, user: pi, alias: iojs-ns-pi1p-11 }
        securogroup-debian10-armv6l_pi1p-2:      {ip: 192.168.2.51, user: pi, alias: iojs-ns-pi1p-12 }
        chrislea-debian10-armv6l_pi1p-1:         {ip: 192.168.2.52, user: pi, alias: iojs-ns-pi1p-13 }
        davglass-debian10-armv6l_pi1p-1:         {ip: 192.168.2.53, user: pi, alias: iojs-ns-pi1p-14 }

        rvagg-debian10-armv7l_pi2-1:        {ip: 192.168.2.60, user: pi, alias: iojs-ns-pi2-1 }
        joeyvandijk-debian10-armv7l_pi2-1:  {ip: 192.168.2.61, user: pi, alias: iojs-ns-pi2-2 }
        joeyvandijk-debian10-armv7l_pi2-2:  {ip: 192.168.2.62, user: pi, alias: iojs-ns-pi2-3 }
        svincent-debian10-armv7l_pi2-1:     {ip: 192.168.2.63, user: pi, alias: iojs-ns-pi2-4 }
        mcollina-debian10-armv7l_pi2-1:     {ip: 192.168.2.64, user: pi, alias: iojs-ns-pi2-5 }
        ceejbot-debian10-armv7l_pi2-1:      {ip: 192.168.2.65, user: pi, alias: iojs-ns-pi2-6 }
        mininodes-debian10-armv7l_pi2-1:    {ip: 192.168.2.66, user: pi, alias: iojs-ns-pi2-7 }
        sambthompson-debian10-armv7l_pi2-1: {ip: 192.168.2.67, user: pi, alias: iojs-ns-pi2-8 }
        louiscntr-debian10-armv7l_pi2-1:    {ip: 192.168.2.68, user: pi, alias: iojs-ns-pi2-9 }
        svincent-debian10-armv7l_pi2-2:     {ip: 192.168.2.69, user: pi, alias: iojs-ns-pi2-10 }
        svincent-debian10-armv7l_pi2-3:     {ip: 192.168.2.70, user: pi, alias: iojs-ns-pi2-11 }
        jasnell-debian10-armv7l_pi2-1:      {ip: 192.168.2.71, user: pi, alias: iojs-ns-pi2-12 }

        williamkapke-debian10-arm64_pi3-1:      {ip: 192.168.2.80, user: pi, alias: iojs-ns-pi3-1 }
        williamkapke-debian10-arm64_pi3-2:      {ip: 192.168.2.81, user: pi, alias: iojs-ns-pi3-2 }
        williamkapke-debian10-arm64_pi3-3:      {ip: 192.168.2.82, user: pi, alias: iojs-ns-pi3-3 }
        davglass-debian10-arm64_pi3-1:          {ip: 192.168.2.83, user: pi, alias: iojs-ns-pi3-4 }
        pivotalagency-debian10-arm64_pi3-1:     {ip: 192.168.2.84, user: pi, alias: iojs-ns-pi3-5 }
        pivotalagency-debian10-arm64_pi3-2:     {ip: 192.168.2.85, user: pi, alias: iojs-ns-pi3-6 }
        securogroup-debian10-arm64_pi3-1:       {ip: 192.168.2.86, user: pi, alias: iojs-ns-pi3-7 }
        securogroup-debian10-arm64_pi3-2:       {ip: 192.168.2.87, user: pi, alias: iojs-ns-pi3-8 }
        notthetup_sayanee-debian10-arm64_pi3-1: {ip: 192.168.2.88, user: pi, alias: iojs-ns-pi3-9 }
        piccoloaiutante-debian10-arm64_pi3-1:   {ip: 192.168.2.89, user: pi, alias: iojs-ns-pi3-10 }
        kahwee-debian10-arm64_pi3-1:            {ip: 192.168.2.90, user: pi, alias: iojs-ns-pi3-11 }

        rvagg-ubuntu1404-arm64_odroidxu3-1: {ip: 192.168.2.10, user: odroid}
        rvagg-ubuntu1404-arm64_odroidxu-1: {ip: 192.168.2.15}
        rvagg-ubuntu1404-arm64_odroidxu-2: {ip: 192.168.2.16}

        osx1010-x64-1: {ip: 192.168.2.210, user: iojs}

    - scaleway:
        ubuntu1804-armv7l-1: {ip: 212.47.233.202}
        ubuntu1804-armv7l-2: {ip: 212.47.246.3}
        ubuntu1804-armv7l-3: {ip: 212.47.227.202}

    - softlayer:
        centos6-x64-1: {ip: 169.61.75.51}
        centos6-x64-2: {ip: 169.61.75.58}
        centos7-x64-1: {ip: 50.23.85.250}
        debian8-x86-1: {ip: 169.44.16.126}
        debian9-x64-1: {ip: 169.60.150.91}
        ubuntu1404-x64-1: {ip: 50.97.245.5}
        ubuntu1404-x86-1: {ip: 50.97.245.9}
        ubuntu1804_docker-x64-1: {ip: 52.117.26.9}

    - packetnet:
        centos7-arm64-1: {ip: 147.75.193.230}
        centos7-arm64-2: {ip: 147.75.74.254}
        ubuntu1604-arm64-1: {ip: 147.75.77.130}
        ubuntu1604-arm64-2: {ip: 147.75.74.174}
# when adding, removing or changing the IPs below,
# remember to update Jenkins worker IP whitelist in github-bot
        ubuntu1804-x64-1: {ip: 147.75.66.203, alias: jenkins-workspace-4}
        ubuntu1804-x64-2: {ip: 147.75.81.67, alias: jenkins-workspace-5}
